name: PRSNet-2
channels:
  - pytorch
  - dglteam/label/th21_cu118
  - nvidia
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - bottleneck=1.4.2=py311hf4808d0_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.16.0=hb05425b_5
  - cffi=1.17.1=py311h1fdaa30_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py311hdb19cb5_0
  - cpython=3.11.13=py311hd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cudatoolkit=11.8.0=h6a678d5_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.8.11=py311h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - deprecated=1.2.13=pyh6c4a22f_0
  - dgl=2.4.0.th21.cu118=py311_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=6.1.1=h2a67f75_3
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=pyhe1237c8_1
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.2.0=hf296adc_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=7.0.1=pyha770c72_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.0.2=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.4.2=pyhd8ed1ab_1
  - jpeg=9e=h166bdaf_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - kiwisolver=1.4.8=py311h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - leptonica=1.82.0=h42c8aad_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libarchive=3.7.7=hfab0078_0
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libclang13=14.0.6=default_he11475f_2
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.147=0
  - libcurl=8.12.1=hc9e6f67_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h516909a_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h69a702a_16
  - libgfortran5=11.2.0=h5c6108e_16
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h516909a_0
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.2=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=he4da1e4_16
  - libtheora=1.1.1=h7f98852_1005
  - libtiff=4.5.1=hffd6297_1
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hce232f5_0
  - libxml2=2.13.5=hfdd30dd_0
  - libxslt=1.1.41=h097e994_0
  - lightgbm=4.6.0=py311h6a678d5_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.10.0=py311h38be061_0
  - matplotlib-base=3.10.0=py311hbfdbfaf_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - minizip=4.0.3=hf59b114_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql=8.4.0=h29a9f33_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.10.1=py311h3c60e43_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.16=h5eee18b_0
  - opentelemetry-api=1.26.0=pyhd8ed1ab_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py311h6a678d5_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh8b19718_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=5.9.0=py311h5eee18b_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.0=pyhd8ed1ab_2
  - pyqt=6.7.1=py311h6a678d5_0
  - pyqt6-sip=13.9.1=py311h5eee18b_0
  - pyside6=6.7.2=py311hfe62871_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.5=h955ad1f_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytorch=2.5.1=py3.11_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=pyhe1237c8_2
  - pyzmq=26.2.0=py311h6a678d5_0
  - qtbase=6.7.2=hdaa5aa8_1
  - qtdeclarative=6.7.2=h6a678d5_0
  - qtshadertools=6.7.2=h6a678d5_0
  - qtsvg=6.7.2=he621ea3_0
  - qttools=6.7.2=h80c7b02_0
  - qtwebchannel=6.7.2=h6a678d5_0
  - qtwebengine=6.7.2=hcbda680_0
  - qtwebsockets=6.7.2=h6a678d5_0
  - readline=8.2=h5eee18b_0
  - scipy=1.15.1=py311h08b1b3b_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=75.8.0=pyhff2d567_0
  - sip=6.10.0=py311h6a678d5_0
  - six=1.16.0=pyhd8ed1ab_1
  - sleef=3.5.1=h9b69904_2
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - tesseract=5.2.0=h6a678d5_2
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.5.1=py311_cu118
  - torchmetrics=1.4.0.post0=pyhd8ed1ab_0
  - torchvision=0.15.2=cuda118py311h4cc2eb7_0
  - tornado=6.4.2=py311h5eee18b_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - tzdata=2025a=h78e105d_0
  - unicodedata2=15.1.0=py311h5eee18b_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.0=py311h5eee18b_0
  - xcb-util-cursor=0.1.4=h5eee18b_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.23.0=py311h2c38b39_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - anndata==0.11.3
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - array-api-compat==1.11.1
      - arrow==1.3.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.5
      - biothings-client==0.4.1
      - bleach==6.2.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - cmake==3.25.0
      - dask==2025.2.0
      - defusedxml==0.7.1
      - einops==0.8.1
      - fastjsonschema==2.21.2
      - filelock==3.16.1
      - fqdn==1.5.1
      - fsspec==2024.10.0
      - h11==0.16.0
      - h5py==3.13.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - isoduration==20.11.0
      - jinja2==3.1.4
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - lark==1.2.2
      - legacy-api-wrap==1.4.1
      - lightning-utilities==0.14.1
      - lit==15.0.7
      - llvmlite==0.44.0
      - locket==1.0.0
      - markupsafe==2.1.5
      - mistune==3.1.4
      - mygene==3.2.2
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - numba==0.61.0
      - nvidia-nccl-cu12==2.27.7
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - partd==1.4.2
      - pillow==11.0.0
      - prometheus-client==0.22.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pynndescent==0.5.13
      - python-json-logger==3.3.0
      - referencing==0.36.2
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.1
      - scanpy==1.11.0
      - scikit-learn==1.5.2
      - send2trash==1.8.3
      - session-info2==0.1.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - statsmodels==0.14.4
      - sympy==1.13.1
      - terminado==0.18.1
      - tinycss2==1.4.0
      - toolz==1.0.0
      - triton==2.0.0
      - types-python-dateutil==2.9.0.20250822
      - umap-learn==0.5.7
      - uri-template==1.3.0
      - urllib3==2.3.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - xgboost==2.1.4
      - zipp==3.21.0
